language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - rbx-18mode

before_script: "sudo ntpdate -ub ntp.ubuntu.com pool.ntp.org; true"
script: "bundle exec rake test"

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: rbx-18mode